# Generated by Django 3.2.16 on 2022-11-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_item_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Comments',
            new_name='comments',
        ),
    ]
