# Generated by Django 3.2.16 on 2022-11-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_rename_comments_item_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='submitted_date',
        ),
    ]
