# Generated by Django 3.2.16 on 2022-11-08 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0007_auto_20221107_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('Pine', 'Pine'), ('Birch', 'Birch'), ('Spruce', 'Spruce')], max_length=15)),
                ('length', models.IntegerField(choices=[(0, '300'), (1, '400'), (2, '500')], default=2)),
                ('width', models.IntegerField()),
                ('thickness', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('deadline', models.DateField()),
                ('quarter_sawn', models.BooleanField(default=False)),
                ('grade', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0)),
                ('comments', models.TextField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Not submitted'), (1, 'Submitted'), (2, 'Quoted')], default=0)),
                ('submitted_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
