# Generated by Django 3.2.16 on 2022-11-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_rename_quotedetails_quotedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedata',
            name='quote_status',
            field=models.CharField(choices=[('Not submitted', 'Not submitted'), ('Submitted', 'Submitted'), ('Quoted', 'Quoted')], default='Not Submitted', max_length=20),
        ),
    ]
