# Generated by Django 3.2.16 on 2022-11-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0010_quotedata_quote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotedata',
            name='status',
        ),
    ]
