# Generated by Django 3.2.16 on 2022-11-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_remove_quotedata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedata',
            name='length_new',
            field=models.CharField(choices=[('300', '300'), ('400', '400'), ('500', '500')], default='400', max_length=10),
        ),
    ]
