# Generated by Django 3.2.16 on 2022-11-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0012_quotedata_length_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedata',
            name='title',
            field=models.CharField(default='10', max_length=20),
        ),
    ]
