# Generated by Django 3.2.16 on 2022-11-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0014_alter_quotedata_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
