# Generated by Django 3.2.16 on 2022-11-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0015_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
