# Generated by Django 3.2.16 on 2022-11-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0016_delete_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotedata',
            name='length',
        ),
    ]
