# Generated by Django 3.2.16 on 2022-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0018_rename_length_new_quotedata_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedata',
            name='quote_status',
            field=models.CharField(choices=[('not_submitted', 'Not submitted'), ('submitted', 'Submitted'), ('quoted', 'Quote Emailed')], default='Not Submitted', max_length=20),
        ),
    ]
