# Generated by Django 3.2.16 on 2022-11-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0019_alter_quotedata_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedata',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not submitted'), (1, 'Submitted'), (2, 'Quote Emailed')], default=0),
        ),
    ]
