# Generated by Django 3.2.16 on 2022-11-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0020_quotedata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotedata',
            name='quote_status',
        ),
    ]
